package com.pmagent.backend.application.recommendation;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.pmagent.backend.infrastructure.entity.ManagedMemberEntity;
import com.pmagent.backend.infrastructure.entity.RecommendationEntity;
import com.pmagent.backend.infrastructure.entity.RequirementEntity;
import com.pmagent.backend.infrastructure.mapper.ManagedMemberMapper;
import com.pmagent.backend.infrastructure.mapper.RecommendationMapper;
import com.pmagent.backend.infrastructure.mapper.RequirementMapper;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@Service
public class WorkspaceRecommendationService {

    private final RequirementMapper requirementMapper;
    private final ManagedMemberMapper managedMemberMapper;
    private final RecommendationMapper recommendationMapper;
    private final ObjectMapper objectMapper;

    public WorkspaceRecommendationService(RequirementMapper requirementMapper,
                                          ManagedMemberMapper managedMemberMapper,
                                          RecommendationMapper recommendationMapper,
                                          ObjectMapper objectMapper) {
        this.requirementMapper = requirementMapper;
        this.managedMemberMapper = managedMemberMapper;
        this.recommendationMapper = recommendationMapper;
        this.objectMapper = objectMapper;
    }

    public Map<String, Object> generate(String workspaceId) {
        List<RequirementEntity> requirements = requirementMapper.listByWorkspaceId(workspaceId);
        if (requirements.isEmpty()) {
            throw new IllegalArgumentException("no_requirements_found");
        }

        List<ManagedMemberEntity> members = managedMemberMapper.listByWorkspaceId(workspaceId);
        String developer = members.stream()
            .filter(it -> !Objects.equals(it.getRole(), "tester") && !Objects.equals(it.getRole(), "qa"))
            .map(ManagedMemberEntity::getMemberName)
            .findFirst()
            .orElse(members.isEmpty() ? "" : members.get(0).getMemberName());
        String tester = members.stream()
            .filter(it -> Objects.equals(it.getRole(), "tester") || Objects.equals(it.getRole(), "qa") || Objects.equals(it.getRole(), "test"))
            .map(ManagedMemberEntity::getMemberName)
            .findFirst()
            .orElse("");

        String now = Instant.now().toString();
        List<Map<String, Object>> created = new ArrayList<>();
        for (RequirementEntity requirement : requirements) {
            Map<String, Object> payload = new HashMap<>();
            payload.put("requirement_id", requirement.getRequirementId());
            payload.put("title", requirement.getTitle());
            payload.put("development_owner", developer);
            payload.put("testing_owner", tester);
            payload.put("backup_owner", "");
            payload.put("collaborators", List.of());
            payload.put("module_name", "");
            payload.put("confidence", 0.6);
            payload.put("reason", "auto-generated by java backend baseline");

            RecommendationEntity entity = new RecommendationEntity();
            entity.setWorkspaceId(workspaceId);
            entity.setRequirementId(requirement.getRequirementId());
            entity.setPayloadJson(writeJson(payload));
            entity.setCreatedAt(now);
            entity.setUpdatedAt(now);
            recommendationMapper.upsert(entity);
            created.add(payload);
        }

        Map<String, Object> response = new HashMap<>();
        response.put("workspaceId", workspaceId);
        response.put("generatedCount", created.size());
        response.put("recommendations", created);
        response.put("updatedAt", now);
        return response;
    }

    public void delete(String workspaceId, String requirementId) {
        int affected = recommendationMapper.deleteByRequirementId(workspaceId, requirementId);
        if (affected != 1) {
            throw new IllegalArgumentException("recommendation_not_found: " + requirementId);
        }
    }

    public Map<String, Object> batchDelete(String workspaceId, List<String> requirementIds) {
        if (requirementIds == null || requirementIds.isEmpty()) {
            return Map.of("workspaceId", workspaceId, "deletedCount", 0);
        }
        int affected = recommendationMapper.batchDelete(workspaceId, requirementIds);
        return Map.of(
            "workspaceId", workspaceId,
            "deletedCount", affected
        );
    }

    public List<Map<String, Object>> list(String workspaceId) {
        return recommendationMapper.listByWorkspaceId(workspaceId).stream()
            .map(entity -> readJson(entity.getPayloadJson()))
            .toList();
    }

    @SuppressWarnings("unchecked")
    private Map<String, Object> readJson(String json) {
        try {
            return objectMapper.readValue(json, Map.class);
        } catch (Exception ex) {
            throw new IllegalArgumentException("invalid recommendation payload json", ex);
        }
    }

    private String writeJson(Map<String, Object> payload) {
        try {
            return objectMapper.writeValueAsString(payload);
        } catch (Exception ex) {
            throw new IllegalArgumentException("failed to serialize recommendation payload", ex);
        }
    }
}
